data:
  data_dir: "data/split"
  image_size: 224
  batch_size: 32
  num_workers: 4

model:
  name: "resnet50"
  pretrained: True
  num_classes: 2
  dropout_rate: 0.5

training:
  epochs: 25
  learning_rate: 0.0001
  weight_decay: 0.0001
  patience: 5

paths:
  checkpoints: "models/model_checkpoints"
  trained_models: "models/trained_models"
  results: "results"